from datetime import datetime
from unittest.mock import MagicMock, patch

import pytest
from sqlalchemy.exc import SQLAlchemyError

from backend.app.domain.entities.comment import Comment
from backend.app.domain.entities.incident import Incident, Severity, State
from backend.app.domain.entities.log import Log, LogLevel
from backend.app.infrastructure.database.repositories import (
    SQLAlchemyCommentRepository,
    SQLAlchemyIncidentRepository,
    SQLAlchemyLogRepository,
)

# ---------- Fixtures ----------

@pytest.fixture
def mock_db_session():
    """Create a mock SQLAlchemy session."""
    session = MagicMock()
    # Mock the query chain: session.query().filter_by().first() / .all()
    mock_query = MagicMock()
    session.query.return_value = mock_query
    mock_filter_by = MagicMock()
    mock_query.filter_by.return_value = mock_filter_by
    mock_filter_by.first.return_value = None
    mock_filter_by.all.return_value = []
    return session


@pytest.fixture
def mock_log_repository():
    """Create a mock log repository."""
    repo = MagicMock()
    repo.create_log.return_value = MagicMock(spec=Log)
    return repo


@pytest.fixture
def comment_repo(mock_db_session, mock_log_repository):
    """SQLAlchemyCommentRepository with mocked dependencies."""
    return SQLAlchemyCommentRepository(mock_db_session, mock_log_repository)


@pytest.fixture
def incident_repo(mock_db_session, mock_log_repository):
    """SQLAlchemyIncidentRepository with mocked dependencies."""
    return SQLAlchemyIncidentRepository(mock_db_session, mock_log_repository)


@pytest.fixture
def log_repo(mock_db_session):
    """SQLAlchemyLogRepository with mocked session."""
    return SQLAlchemyLogRepository(mock_db_session)


# ---------- Helper to create domain entities ----------
def create_domain_comment(id=1, content="test", author_id=10, incident_id=100, timestamp=None):
    if timestamp is None:
        timestamp = datetime.now()
    return Comment(id=id, content=content, author_id=author_id,
                   incident_id=incident_id, timestamp=timestamp)

def create_domain_incident(id=1, title="Test", description="Desc", severity=Severity.MEDIUM,
                           state=State.OPEN, assigned_to=5, created_at=None, updated_at=None):
    if created_at is None:
        created_at = datetime.now()
    if updated_at is None:
        updated_at = datetime.now()
    return Incident(id=id, title=title, description=description, severity=severity,
                    state=state, assigned_to=assigned_to, created_at=created_at,
                    updated_at=updated_at, summary_id=None)

def create_domain_log(id=1, message="msg", log_level=LogLevel.INFO, timestamp=None):
    if timestamp is None:
        timestamp = datetime.now()
    return Log(id=id, message=message, log_level=log_level, timestamp=timestamp)


# ---------- Tests for SQLAlchemyCommentRepository ----------
class TestSQLAlchemyCommentRepository:
    def test_create_comment_success(self, comment_repo, mock_db_session, mock_log_repository):
        domain_comment = create_domain_comment(id=None)  # id generated by DB
        # Mock DBComment instance
        mock_db_comment = MagicMock()
        mock_db_comment.id = 42
        mock_db_comment.content = domain_comment.content
        mock_db_comment.author_id = domain_comment.author_id
        mock_db_comment.incident_id = domain_comment.incident_id
        mock_db_comment.timestamp = domain_comment.timestamp

        with patch("backend.app.infrastructure.database.repositories.comment_repo_imp.DBComment",
               return_value=mock_db_comment):
            result = comment_repo.create_comment(domain_comment)

        mock_db_session.add.assert_called_once_with(mock_db_comment)
        mock_db_session.commit.assert_called_once()
        mock_db_session.refresh.assert_called_once_with(mock_db_comment)
        mock_log_repository.create_log.assert_called_once()
        assert result.id == 42
        assert result.content == domain_comment.content

    def test_create_comment_db_error(self, comment_repo, mock_db_session, mock_log_repository):
        domain_comment = create_domain_comment()
        mock_db_session.commit.side_effect = SQLAlchemyError("DB error")

        with patch("backend.app.infrastructure.database.repositories.comment_repo_imp.DBComment",
               return_value=MagicMock()):
            with pytest.raises(RuntimeError, match="Database error: DB error"):
                comment_repo.create_comment(domain_comment)

        mock_db_session.rollback.assert_called_once()
        mock_log_repository.create_log.assert_called_once()
        log_call = mock_log_repository.create_log.call_args[0][0]
        assert log_call.log_level == LogLevel.ERROR
        assert "Failed to create comment" in log_call.message

    def test_get_comment_by_id_found(self, comment_repo, mock_db_session):
        mock_db_comment = MagicMock()
        mock_db_comment.id = 1
        mock_db_comment.content = "found"
        mock_db_comment.author_id = 10
        mock_db_comment.incident_id = 100
        mock_db_comment.timestamp = datetime.now()
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_db_comment

        result = comment_repo.get_comment_by_id(1)
        assert result is not None
        assert result.id == 1

    def test_get_comment_by_id_not_found(self, comment_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        result = comment_repo.get_comment_by_id(999)
        assert result is None

    def test_get_comment_by_id_db_error(self, comment_repo, mock_db_session, mock_log_repository):
        mock_db_session.query.side_effect = SQLAlchemyError("query fail")
        with pytest.raises(RuntimeError, match="Database error: query fail"):
            comment_repo.get_comment_by_id(1)
        mock_log_repository.create_log.assert_called_once()

    def test_update_comment_success(self, comment_repo, mock_db_session, mock_log_repository):
        existing_db_comment = MagicMock()
        existing_db_comment.id = 5
        existing_db_comment.content = "old"
        existing_db_comment.timestamp = datetime.now()
        existing_db_comment.incident_id = 200
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = existing_db_comment

        updated_domain = create_domain_comment(id=5, content="new content")
        result = comment_repo.update_comment(updated_domain)

        assert existing_db_comment.content == "new content"
        existing_db_comment.timestamp = updated_domain.timestamp  # ensure assignment
        mock_db_session.commit.assert_called_once()
        mock_log_repository.create_log.assert_called_once()
        assert result.content == "new content"

    def test_update_comment_not_found(self, comment_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        domain_comment = create_domain_comment(id=5)
        with pytest.raises(ValueError, match="Comment not found"):
            comment_repo.update_comment(domain_comment)

    def test_update_comment_db_error(self, comment_repo, mock_db_session, mock_log_repository):
        existing_db_comment = MagicMock()
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = existing_db_comment
        mock_db_session.commit.side_effect = SQLAlchemyError("update fail")
        domain_comment = create_domain_comment(id=5)
        with pytest.raises(RuntimeError, match="Database error: update fail"):
            comment_repo.update_comment(domain_comment)
        mock_db_session.rollback.assert_called_once()
        mock_log_repository.create_log.assert_called_once()

    def test_delete_comment_success(self, comment_repo, mock_db_session, mock_log_repository):
        existing_db_comment = MagicMock()
        existing_db_comment.id = 7
        existing_db_comment.incident_id = 300
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = existing_db_comment

        comment_repo.delete_comment(7)

        mock_db_session.delete.assert_called_once_with(existing_db_comment)
        mock_db_session.commit.assert_called_once()
        mock_log_repository.create_log.assert_called_once()

    def test_delete_comment_not_found(self, comment_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        with pytest.raises(ValueError, match="Comment not found"):
            comment_repo.delete_comment(99)

    def test_list_comments_by_incident_id(self, comment_repo, mock_db_session):
        mock_db_comment1 = MagicMock(id=1, content="c1", author_id=10, incident_id=5, timestamp=datetime.now())
        mock_db_comment2 = MagicMock(id=2, content="c2", author_id=20, incident_id=5, timestamp=datetime.now())
        mock_db_session.query.return_value.filter_by.return_value.all.return_value = [mock_db_comment1, mock_db_comment2]

        results = comment_repo.list_comments_by_incident_id(5)
        assert len(results) == 2
        assert results[0].id == 1
        assert results[1].id == 2

    def test_list_comments_by_author_id(self, comment_repo, mock_db_session):
        mock_db_comment = MagicMock(id=3, content="by author", author_id=42, incident_id=7, timestamp=datetime.now())
        mock_db_session.query.return_value.filter_by.return_value.all.return_value = [mock_db_comment]
        results = comment_repo.list_comments_by_author_id(42)
        assert len(results) == 1
        assert results[0].author_id == 42


# ---------- Tests for SQLAlchemyIncidentRepository ----------
class TestSQLAlchemyIncidentRepository:
    def test_create_incident_success(self, incident_repo, mock_db_session, mock_log_repository):
        domain_incident = create_domain_incident(id=None)
        mock_db_incident = MagicMock()
        mock_db_incident.id = 10
        with patch("backend.app.infrastructure.database.repositories.incident_repo_imp.DBIncident",
               return_value=mock_db_incident):
            result = incident_repo.create_incident(domain_incident)

        mock_db_session.add.assert_called_once_with(mock_db_incident)
        mock_db_session.commit.assert_called_once()
        mock_db_session.refresh.assert_called_once_with(mock_db_incident)
        mock_log_repository.create_log.assert_called_once()
        assert result.id == 10

    def test_create_incident_db_error(self, incident_repo, mock_db_session, mock_log_repository):
        domain_incident = create_domain_incident()
        mock_db_session.commit.side_effect = SQLAlchemyError("creation error")
        with patch("backend.app.infrastructure.database.repositories.incident_repo_imp.DBIncident", return_value=MagicMock()):
            with pytest.raises(RuntimeError, match="Database error: creation error"):
                incident_repo.create_incident(domain_incident)
        mock_db_session.rollback.assert_called_once()
        mock_log_repository.create_log.assert_called_once()

    def test_get_incident_by_id_found(self, incident_repo, mock_db_session):
        mock_db_incident = MagicMock()
        mock_db_incident.id = 1
        mock_db_incident.title = "test"
        mock_db_incident.description = "desc"
        mock_db_incident.severity = Severity.HIGH
        mock_db_incident.state = State.IN_PROGRESS
        mock_db_incident.assigned_to = 2
        mock_db_incident.created_at = datetime.now()
        mock_db_incident.updated_at = datetime.now()
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_db_incident

        result = incident_repo.get_incident_by_id(1)
        assert result.id == 1

    def test_get_incident_by_id_not_found(self, incident_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        assert incident_repo.get_incident_by_id(999) is None

    def test_update_incident_success(self, incident_repo, mock_db_session, mock_log_repository):
        existing = MagicMock()
        existing.id = 5
        existing.title = "old"
        existing.description = "old desc"
        existing.state = State.OPEN
        existing.severity = Severity.LOW
        existing.assigned_to = 1
        existing.updated_at = datetime.now()
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = existing

        incident_repo.update_incident(create_domain_incident(id=5, title="new", description="new desc", state=State.CLOSED))

        assert existing.title == "new"
        assert existing.state == State.CLOSED
        mock_db_session.commit.assert_called_once()
        mock_log_repository.create_log.assert_called_once()

    def test_update_incident_not_found(self, incident_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        domain_incident = create_domain_incident(id=5)
        with pytest.raises(ValueError, match="Incident not found"):
            incident_repo.update_incident(domain_incident)

    def test_delete_incident_success(self, incident_repo, mock_db_session, mock_log_repository):
        existing = MagicMock()
        existing.id = 7
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = existing
        incident_repo.delete_incident(7)
        mock_db_session.delete.assert_called_once_with(existing)
        mock_db_session.commit.assert_called_once()
        mock_log_repository.create_log.assert_called_once()

    def test_delete_incident_not_found(self, incident_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        with pytest.raises(ValueError, match="Incident not found"):
            incident_repo.delete_incident(99)

    def test_list_incidents(self, incident_repo, mock_db_session):
        mock_db_incident = MagicMock(id=1)
        mock_db_session.query.return_value.all.return_value = [mock_db_incident]
        results = incident_repo.list_incidents()
        assert len(results) == 1

    def test_list_incidents_by_assigned_user(self, incident_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.all.return_value = [MagicMock(id=1), MagicMock(id=2)]
        results = incident_repo.list_incidents_by_assigned_user(5)
        assert len(results) == 2
        mock_db_session.query.return_value.filter_by.assert_called_with(assigned_to=5)

    def test_list_incidents_by_severity(self, incident_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.all.return_value = []
        results = incident_repo.list_incidents_by_severity(Severity.CRITICAL)
        assert results == []
        mock_db_session.query.return_value.filter_by.assert_called_with(severity=Severity.CRITICAL)

    def test_list_incidents_by_state(self, incident_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.all.return_value = [MagicMock()]
        results = incident_repo.list_incidents_by_state(State.RESOLVED)
        assert len(results) == 1


# ---------- Tests for SQLAlchemyLogRepository ----------
class TestSQLAlchemyLogRepository:
    def test_create_log_success(self, log_repo, mock_db_session):
        domain_log = create_domain_log(id=None)
        mock_db_log = MagicMock()
        mock_db_log.id = 5
        with patch("backend.app.infrastructure.database.repositories.log_repo_imp.DBLog",
               return_value=mock_db_log):
            result = log_repo.create_log(domain_log)

        mock_db_session.add.assert_called_once_with(mock_db_log)
        mock_db_session.commit.assert_called_once()
        mock_db_session.refresh.assert_called_once_with(mock_db_log)
        assert result.id == 5

    def test_create_log_db_error(self, log_repo, mock_db_session):
        domain_log = create_domain_log()
        mock_db_session.commit.side_effect = SQLAlchemyError("log error")
        with patch("backend.app.infrastructure.database.repositories.log_repo_imp.DBLog", return_value=MagicMock()):
            with pytest.raises(RuntimeError, match="Database error: log error"):
                log_repo.create_log(domain_log)
        mock_db_session.rollback.assert_called_once()

    def test_get_log_by_id_found(self, log_repo, mock_db_session):
        mock_db_log = MagicMock()
        mock_db_log.id = 10
        mock_db_log.message = "test"
        mock_db_log.log_level = LogLevel.INFO
        mock_db_log.timestamp = datetime.now()
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_db_log

        result = log_repo.get_log_by_id(10)
        assert result.id == 10

    def test_get_log_by_id_not_found(self, log_repo, mock_db_session):
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        assert log_repo.get_log_by_id(999) is None

    def test_list_logs(self, log_repo, mock_db_session):
        mock_db_log1 = MagicMock(id=1)
        mock_db_log2 = MagicMock(id=2)
        mock_db_session.query.return_value.all.return_value = [mock_db_log1, mock_db_log2]
        results = log_repo.list_logs()
        assert len(results) == 2
